classdef JsonCodecTest < matlab.unittest.TestCase
%JsonCodecTest Tests for JSON encoding/decoding of option values

    methods (TestClassSetup)
        function addCodeToPath(testCase)
            rootPath = fileparts(fileparts(fileparts(mfilename("fullpath"))));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(rootPath, "code"), IncludingSubfolders=true))
        end
    end

    properties (TestParameter)
        value = struct( ...
            "scalar", 1, ...
            "rowVector", [1, 2, 3], ...
            "columnVector", [1; 2], ...
            "matrix", magic(3), ...
            "nan", NaN, ...
            "inf", [1, Inf, -Inf], ...
            "int", int16([1, 2]), ...
            "int64", int64(-5), ...
            "emptyDouble", [], ...
            "emptyRow", zeros(1, 0), ...
            "text", 'hello', ...
            "emptyText", '', ...
            "emptyTextRow", char(zeros(1, 0)), ...
            "charMatrix", ['ab'; 'cd'], ...
            "stringArray", ["a", "b"], ...
            "stringColumn", ["a"; "b"], ...
            "emptyStringArray", strings(1, 0), ...
            "cellstr", {{'a', 'b'}}, ...
            "singleCellstr", {{'a'}}, ...
            "emptyCell", {{}}, ...
            "mixedCell", {{1, 'a', [1, 2]}}, ...
            "nestedCell", {{{1, 2}, {'a'}}}, ...
            "logical", true, ...
            "logicalRow", [true, false], ...
            "structArray", struct("a", {1, 2}), ...
            "emptyStruct", struct("a", {}), ...
            "noFieldStruct", struct(), ...
            "emptyNoFieldStruct", repmat(struct(), 1, 0), ...
            "datetime", datetime(2024, 1, 2, 3, 4, 5.5, TimeZone="UTC"))
        % Note: Values of NANSEN classes are tested in separate tests, as
        % test parameters are created before the path is set up.
    end

    methods (Test)
        function testRoundTrip(testCase, value)
            S = struct("value", {value});
            jsonStr = nansen.options.internal.jsonEncode(S);
            decoded = nansen.options.internal.jsonDecode(jsonStr);

            testCase.verifyEqual(decoded.value, value)
            testCase.verifyClass(decoded.value, class(value))
            testCase.verifySize(decoded.value, size(value))
        end

        function testEnumerationRoundTrip(testCase)
            values = {nansen.options.ParameterType.Numeric, ...
                [nansen.options.ProfileType.User, nansen.options.ProfileType.Preset]};
            for i = 1:numel(values)
                decoded = roundTrip(values{i});
                testCase.verifyEqual(decoded, values{i})
            end
        end
        
        function testMissingStringRoundTrip(testCase)
            values = {["a", missing], string(missing), [missing, missing]};
            for i = 1:numel(values)
                decoded = roundTrip(values{i});
                testCase.verifyClass(decoded, "string")
                testCase.verifySize(decoded, size(values{i}))
                testCase.verifyEqual(ismissing(decoded), ismissing(values{i}))
                testCase.verifyEqual(decoded(~ismissing(decoded)), values{i}(~ismissing(values{i})))
            end
        end
        
        function testFunctionHandleRoundTrip(testCase)
            S = struct("fcn", @(x) x + 1);
            decoded = nansen.options.internal.jsonDecode( ...
                nansen.options.internal.jsonEncode(S));
            testCase.verifyEqual(func2str(decoded.fcn), func2str(S.fcn))
        end

        function testCommonValuesArePlainJson(testCase)
            S = struct("a", 1, "b", [1, 2], "c", 'x', "d", {{'x', 'y'}}, "e", true, "f", "y");
            jsonStr = nansen.options.internal.jsonEncode(S, PrettyPrint=false);
            testCase.verifyEqual(jsonStr, ...
                "{""a"":1,""b"":[1,2],""c"":""x"",""d"":[""x"",""y""],""e"":true,""f"":""y""}")
        end
    end
end

function decoded = roundTrip(value)
    S = struct("value", {value});
    decoded = nansen.options.internal.jsonDecode(nansen.options.internal.jsonEncode(S));
    decoded = decoded.value;
end
