classdef JsonCodecTest < matlab.unittest.TestCase
%JsonCodecTest Tests for JSON encoding/decoding of option values

    methods (TestClassSetup)
        function addCodeToPath(testCase)
            rootPath = fileparts(fileparts(fileparts(mfilename('fullpath'))));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(rootPath, 'code'), 'IncludingSubfolders', true))
        end
    end

    properties (TestParameter)
        value = struct( ...
            'scalar', 1, ...
            'rowVector', [1, 2, 3], ...
            'columnVector', [1; 2], ...
            'matrix', magic(3), ...
            'nan', NaN, ...
            'inf', [1, Inf, -Inf], ...
            'int', int16([1, 2]), ...
            'int64', int64(-5), ...
            'emptyTextRow', char(zeros(1, 0)), ...
            'emptyDouble', [], ...
            'emptyRow', zeros(1, 0), ...
            'text', 'hello', ...
            'emptyText', '', ...
            'charMatrix', ['ab'; 'cd'], ...
            'cellstr', {{'a', 'b'}}, ...
            'singleCellstr', {{'a'}}, ...
            'emptyCell', {{}}, ...
            'mixedCell', {{1, 'a', [1, 2]}}, ...
            'nestedCell', {{{1, 2}, {'a'}}}, ...
            'logical', true, ...
            'logicalRow', [true, false], ...
            'structArray', struct('a', {1, 2}), ...
            'emptyStruct', struct('a', {}), ...
            'noFieldStruct', struct())
    end

    methods (Test)
        function testRoundTrip(testCase, value)
            S = struct('value', {value});
            jsonStr = nansen.options.internal.jsonEncode(S);
            decoded = nansen.options.internal.jsonDecode(jsonStr);

            testCase.verifyEqual(decoded.value, value)
            testCase.verifyClass(decoded.value, class(value))
        end

        function testFunctionHandleRoundTrip(testCase)
            S = struct('fcn', @(x) x + 1);
            decoded = nansen.options.internal.jsonDecode( ...
                nansen.options.internal.jsonEncode(S));
            testCase.verifyEqual(func2str(decoded.fcn), func2str(S.fcn))
        end

        function testCommonValuesArePlainJson(testCase)
            S = struct('a', 1, 'b', [1, 2], 'c', 'x', 'd', {{'x', 'y'}}, 'e', true);
            jsonStr = nansen.options.internal.jsonEncode(S, false);
            testCase.verifyEqual(jsonStr, '{"a":1,"b":[1,2],"c":"x","d":["x","y"],"e":true}')
        end
    end
end
